version: "3.7"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn hckthn.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  frontend:
    volumes:
      - react-build:/home/frontend/build
    build: ./frontend
  nginx:
    image: nginx:stable-alpine
    entrypoint: nginx -g 'daemon off;'
    volumes:
      - react-build:/build
      -  ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    depends_on:
      - frontend

volumes:
  postgres_data:
  react-build:
