version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hckthn.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: take-pills-bot
    environment:
      MONGODB_DATABASE: project
      MONGODB_USERNAME: mongorootuser
      MONGODB_PASSWORD: PswdRoot
      MONGODB_HOSTNAME: mongodb
      MONGODB_PORT: 27017
      TZ: Europe/Moscow
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongorootuser
      MONGO_INITDB_ROOT_PASSWORD: PswdRoot
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      TZ: Europe/Moscow

volumes:
  postgres_data:
  media_volume:
