version: "3.7"

services:
  redis:
    image: "redis:alpine"
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=base_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackathon_dev
  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
