version: "3.7"

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=base_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackathon_dev
  # bot:
  #   build:
  #     context: bot
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   container_name: take-pills-bot
  #   environment:
  #     MONGODB_DATABASE: project
  #     MONGODB_USERNAME: mongorootuser
  #     MONGODB_PASSWORD: PswdRoot
  #     MONGODB_HOSTNAME: mongodb
  #     MONGODB_PORT: 27017
  #     TZ: Europe/Moscow
  #   links:
  #     - mongodb
  # mongodb:
  #   image: mongo:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./mongodb/data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongorootuser
  #     MONGO_INITDB_ROOT_PASSWORD: PswdRoot
  #     MONGODB_DATA_DIR: /data/db
  #     MONDODB_LOG_DIR: /dev/null
  #     TZ: Europe/Moscow
volumes:
  postgres_data:
