# Generated by Django 3.2.2 on 2021-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210507_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column_order',
            field=models.IntegerField(),
        ),
    ]
